name: theia-ide
version: 1.66.200
license: EPL-2.0 AND GPL-2.0-with-classpath-exception AND MIT
website: https://theia-ide.org/
source-code: https://github.com/eclipse-theia
donation: https://www.eclipse.org/sponsor/ide/
summary: Eclipse Theia IDE
description: Open, Flexible and Extensible Cloud & Desktop IDE
base: core24
grade: stable
confinement: classic
compression: lzo
platforms:
  amd64:
    build-on: amd64
    build-for: amd64
apps:
  theia-ide:
    command: opt/TheiaIDE/theia-ide-electron-app
    desktop: usr/share/applications/theia-ide-electron-app.desktop
    common-id: theia-ide-electron-app.desktop
parts:
  theia-ide:
    source: https://download.eclipse.org/theia/ide/1.66.200/linux/TheiaIDE.deb
    plugin: dump
    source-type: deb
    override-prime: |
      craftctl default
      sed -i -Ee 's|^Icon=(.*)$|Icon=/usr/share/icons/hicolor/512x512/apps/\1.png|' $SNAPCRAFT_PRIME/usr/share/applications/theia-ide-electron-app.desktop
    stage-packages:
      - libx11-6
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxrandr2
      - libasound2t64
      - libatk1.0-0t64
      - libatk-bridge2.0-0t64
      - libatspi2.0-0t64
      - libcairo2
      - libcups2t64
      - libgbm1
      - libgtk-3-0t64
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libxcb1
